# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9325d2056e2a513380ed4c273fa96b578f04b91d603917df110880da4af5521a8cc883562e888e42ae346387548a4a512997c5002cf096d1dbc7180016c07111

test:
  secret_key_base: 72bcbe4c5e60d4143ac43e945cb659188c1dd71fff5a6e514eb2b4feabe199ce5be3ef626aa03c91c1b8f3d99f3ab22226e4ce2b72da02508e5b96dc29053892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
